#
# ---Traveller/Contact Details Variables---
#
lbl_TravellerContact = '[NAME:grpBookingContact]'
lbl_FirstName = '[NAME:lblFirstName]'
lbl_MiddleName = '[NAME:lblMiddleName]'
lbl_LastName = '[NAME:lblLastName]'
edt_FirstName = '[NAME:CtxtFirstName]'
edt_MiddleName = '[NAME:CtxtMiddleName]'	
edt_LastName = '[NAME:CtxtLastName]'
lbl_Email = '[NAME:lblEmail]'
edt_Email = '[NAME:CtxtEmail]'
lbl_Telephone = '[NAME:lblTelephone]'
edt_Telephone = '[NAME:CtxtTelephone]'
lbl_Mobile = '[NAME:lblMobile]'
edt_Mobile = '[NAME:CtxtMobile]'
lbl_Profile = '[NAME:lblProfile]'
lbl_Traveller = '[NAME:lblTraveller]'
chkbx_Traveller = '[NAME:CchkTraveller]'
lbl_Arranger = '[NAME:lblArranger]'
chkbx_Arranger = '[NAME:CchkArranger]'
lbl_DOB = '[NAME:lblDOB]'
lbl_Gender = '[NAME:lblGender]'
lbl_Redress = '[NAME:lblRedress]'
drpdwn_DOB = '[NAME:dtpDate]'
drpdwn_Gender = '[NAME:CcboGender]'
edt_Redress = '[NAME:CtxtRedressNumber]'
cbo_Client = '[NAME:ccboCompany]'
crad_KDS = '[NAME:rbKDS]'
edit_lastName = '[NAME:ctxtPortraitTravellerLastName]'
edit_firstName = '[NAME:ctxtPortraitTravellerFirstName]'