#***Variables***
#Documentation: Houses all the control objects for PEX pspt and visa Panel only.
#
# Pspt and Visa panel objects
#
travel_document_details = '[NAME:grpPassport]'
combo_documenttype = '[NAME:ccboDocumentType0]'
combo_documenttype_0 = '[NAME:ccboDocumentType0]'
combo_documenttype_1 = '[NAME:ccboDocumentType1]'
combo_documenttype_2 = '[NAME:ccboDocumentType2]'
combo_documenttype_3 = '[NAME:ccboDocumentType3]'
combo_documenttype_4 = '[NAME:ccboDocumentType4]'
combo_nationality_citizenship = '[NAME:ccboNationality0]'
combo_nationality_citizenship_0 = '[NAME:ccboNationality0]'
combo_nationality_citizenship_1 = '[NAME:ccboNationality1]'
combo_nationality_citizenship_2 = '[NAME:ccboNationality2]'
combo_nationality_citizenship_3 = '[NAME:ccboNationality3]'
combo_nationality_citizenship_4 = '[NAME:ccboNationality4]'
text_docnumber = '[NAME:ctxtPassportNumber0]'
text_docnumber0 = '[NAME:ctxtPassportNumber0]'
text_docnumber1 = '[NAME:ctxtPassportNumber1]'
text_docnumber2 = '[NAME:ctxtPassportNumber2]'
text_docnumber3 = '[NAME:ctxtPassportNumber3]'
text_docnumber4 = '[NAME:ctxtPassportNumber4]'
date_expirydate_0 = '[NAME:cdtpExpiryDate0]'
date_expirydate_1 = '[NAME:cdtpExpiryDate1]'
date_expirydate_2 = '[NAME:cdtpExpiryDate2]'
date_expirydate_3 = '[NAME:cdtpExpiryDate3]'
date_expirydate_4 = '[NAME:cdtpExpiryDate4]'
doc_validity_0 = '[NAME:ccboPassportValid0]'
combo_docvalid_0 = '[NAME:ccboPassportValid0]'
combo_docvalid_1 = '[NAME:ccboPassportValid1]'
combo_docvalid_2 = '[NAME:ccboPassportValid2]'
combo_docvalid_3 = '[NAME:ccboPassportValid3]'
combo_docvalid_4 = '[NAME:ccboPassportValid4]'
combo_docvalid_5 = '[NAME:ccboPassportValid5]'
combo_visa_required_0 = '[NAME:ccboVisa0]'
combo_visa_required_1 = '[NAME:ccboVisa1]'
combo_visa_required_2 = '[NAME:ccboVisa2]'
combo_visa_required_3 = '[NAME:ccboVisa3]'
combo_visa_required_4 = '[NAME:ccboVisa4]'
combo_country_visited_0 = '[NAME:ctxtCountries0]'
combo_country_visited_1 = '[NAME:ctxtCountries1]'
combo_country_visited_2 = '[NAME:ctxtCountries2]'
combo_country_visited_3 = '[NAME:ctxtCountries3]'
combo_country_visited_4 = '[NAME:ctxtCountries4]'
combo_esta_prompt = '[NAME:ccboESTA]'
check_box_domestic_trip = '[NAME:cchkDomesticTrip]'
check_box_select_passport = '[NAME:chkSelectPassport0]'
check_box_select_passport_0 = '[NAME:chkSelectPassport0]'
check_box_select_passport_1 = '[NAME:chkSelectPassport1]'
check_box_select_passport_2 = '[NAME:chkSelectPassport2]'
check_box_select_passport_3 = '[NAME:chkSelectPassport3]'
check_box_select_passport_4 = '[NAME:chkSelectPassport4]'
button_add_passport = '[NAME:btnAddPassport]'
group_visa_details = '[NAME:grpVisaDetails]'
combo_country_residence = '[NAME:ccboCountryResidence]'
visa_requirements = '[NAME:grpVisa]'
view_pp_and_visa_info = '[NAME:txtPassportVisaInfo]'
button_remove_passport_0 = '[NAME:btnRemovePassport0]'
button_remove_passport_1 = '[NAME:btnRemovePassport1]'
button_remove_passport_2 = '[NAME:btnRemovePassport2]'
button_remove_passport_3 = '[NAME:btnRemovePassport3]'
button_remove_passport_4 = '[NAME:btnRemovePassport4]'
combo_compliant = '[NAME:ccboCompliantOBT_1]'

#
# -------------------------------- End of file -------------------------------------
