#***Variables***
#Documentation: Houses all the control objects for PEX Recap Panel only.
#
# Recap panel objects
#
combo_bookingmethod = '[NAME:ccboBookingMethod]'
combo_skip_entries = '[NAME:ccboSkipEntries]'
combo_skip_entries_3 = '[NAME:ccboSkipEntries3]'
combo_skip_entries_4 = '[NAME:ccboSkipEntries4]'
edit_text_back_office_number = '[NAME:ctxtBackOfficeNumber]'
button_add_skip_entries = '[NAME:cmdAddSE]'
button_delete_skip_entries = '[NAME:cmdDeleteSE]'
button_add_general_remark = '[NAME:cmdAddGeneralRemark]'
button_add_gr_0 = '[NAME:cmdAddGR0]'
button_add_gr_1 = '[NAME:cmdAddGR1]'
button_add_gr_2 = '[NAME:cmdAddGR2]'
button_delete_gr_0 = '[NAME:cmdDeleteGR0]'
button_delete_gr_1 = '[NAME:cmdDeleteGR1]'
button_delete_gr_2 = '[NAME:cmdDeleteGR2]'
button_add_queue_minder = '[NAME:cmdAddQueueMinder]'
button_add_qm_0 = '[NAME:cmdAddQM0]'
button_add_qm_1 = '[NAME:cmdAddQM1]'
button_add_qm_2 = '[NAME:cmdAddQM2]'
button_add_qm_3 = '[NAME:cmdAddQM3]'
button_add_qm_4 = '[NAME:cmdAddQM4]'
button_delete_qm_0 = '[NAME:cmdDeleteQM0]'
button_delete_qm_1 = '[NAME:cmdDeleteQM1]'
button_delete_qm_2 = '[NAME:cmdDeleteQM2]'
button_delete_qm_3 = '[NAME:cmdDeleteQM3]'
button_delete_qm_4 = '[NAME:cmdDeleteQM4]'
button_delete_qm_4 = '[NAME:cmdDeleteQM5]'
combo_remark_qualifier_0 = '[NAME:ccboRemarkQualifier0]'
combo_remark_qualifier_1 = '[NAME:ccboRemarkQualifier1]'
combo_remark_qualifier_2 = '[NAME:ccboRemarkQualifier2]'
edit_text_remark_0 = '[NAME:ctxtRemarkText0]'
edit_text_remark_1 = '[NAME:ctxtRemarkText1]'
edit_text_remark_2 = '[NAME:ctxtRemarkText2]'
dt_queue_minders_date_0 = '[NAME:cdtpDate0]'
dt_queue_minders_date_1 = '[NAME:cdtpDate1]'
dt_queue_minders_date_2 = '[NAME:cdtpDate2]'
dt_queue_minders_date_3 = '[NAME:cdtpDate3]'
dt_queue_minders_date_4 = '[NAME:cdtpDate4]'
edit_queue_minders_queue_0 = '[NAME:ctxtQueue0]'
edit_queue_minders_pcc_0 = '[NAME:ctxtPCC0]'
edit_queue_minders_cat_0 = '[NAME:ctxtCategory0]'
edit_queue_minders_queue_1 = '[NAME:ctxtQueue1]'
edit_queue_minders_pcc_1 = '[NAME:ctxtPCC1]'
edit_queue_minders_cat_1 = '[NAME:ctxtCategory1]'
edit_queue_minders_queue_2 = '[NAME:ctxtQueue2]'
edit_queue_minders_pcc_2 = '[NAME:ctxtPCC2]'
edit_queue_minders_cat_2 = '[NAME:ctxtCategory2]'
edit_queue_minders_queue_3 = '[NAME:ctxtQueue3]'
edit_queue_minders_pcc_3 = '[NAME:ctxtPCC3]'
edit_queue_minders_cat_3 = '[NAME:ctxtCategory3]'
edit_queue_minders_queue_4 = '[NAME:ctxtQueue4]'
edit_queue_minders_pcc_4 = '[NAME:ctxtPCC4]'
edit_queue_minders_cat_4 = '[NAME:ctxtCategory4]'
edit_queue_minders_time_0 = '[NAME:cmtxTime0]'
edit_queue_minders_time_1 = '[NAME:cmtxTime1]'
edit_queue_minders_time_2 = '[NAME:cmtxTime2]'
edit_queue_minders_time_3 = '[NAME:cmtxTime3]'
edit_queue_minders_time_4 = '[NAME:cmtxTime4]'
text_of_payment = '[NAME:ctxtFormOfPayment]'
edit_queue_minders_msg_0 = '[NAME:ctxtMessage0]'
edit_queue_minders_msg_1 = '[NAME:ctxtMessage1]'
edit_queue_minders_msg_2 = '[NAME:ctxtMessage2]'
edit_queue_minders_msg_3 = '[NAME:ctxtMessage3]'
edit_queue_minders_msg_4 = '[NAME:ctxtMessage4]'
clipper_compliancy_options = '[NAME:ccboCompliancy]'
select_nr_of_pnrs = '[NAME:ccboSelectPnr]'
edit_pcc = '[NAME:ctxtPCC]'
edit_teamid = '[NAME:ctxtTeamName]'
label_automation_options = '[NAME:grpAutomationOptions]'
check_box_OfflineRequestNumber = '[NAME:cchkOfflineRequestNumber]'
text_OfflineRequestNumber = '[NAME:ctxtOfflineRequestNumber]'
edit_moxie_incident_id = '[NAME:ctxtMoxieIncidentId]'
#
#
# -------------------------------- End of file -------------------------------------
