#***Variables***
#Documentation: Houses all the control objects for PEX APIS/SFPD Panel only.
#
# APIS/SFPD PANEL CONTROL OBJECTS
#
label_FirstNameSFPD = '[NAME:lblFirstNameSFPD]'
label_MiddleNameSFPD = '[NAME:lblMiddleNameSFPD]'
label_LastNameSFPD = '[NAME:lblLastNameSFPD]'
check_box_notknown = '[NAME:chkSFPD]'
check_box_notknown2 = '[NAME:chkPaxDetails]'
check_box_notknown3 = '[NAME:chkOtherDetails]'
check_box_notknown4 = '[NAME:chkAddress]'
edit_first_name_sfpd = '[NAME:ctxtFirstNameSFPD]'
edit_middle_name_sfpd = '[NAME:ctxtMiddleNameSFPD]'
edit_last_name_sfpd = '[NAME:ctxtLastNameSFPD]'
edit_dob_sfpd = '[NAME:cdtpDateOfBirthSFPD]'
combo_gender_sfpd = '[NAME:ccboGenderSFPD]'
edit_redress_number = '[NAME:ctxtRedressNumber]'
edit_known_traveller_number = '[NAME:ctxtKnownTravelerNumber]'
edit_dob_paxdetails = '[NAME:cdtpDateOfBirth]'
combo_gender_paxdetails = '[NAME:ccboGender]'
edit_dob_sfpd2 = '[NAME:cdtpDateOfBirth]'
radio_address_Home = '[NAME:cradHome]'
radio_address_Destination = '[NAME:cradDestination]'
edit_address_street = '[NAME:ctxtAddressStreet]'
edit_address_city = '[NAME:ctxtAddressCity]'
combo_address_country = '[NAME:ccboAddressCountry]'
combo_address_statecode = '[NAME:ccboAddressStateCode]'
combo_country_of_issue = '[NAME:ccboCountryOfIssue]'
edit_nationality_Citizenship = '[NAME:ccboNationality]'
combo_document_type_apis = '[NAME:ccboDocumentType]'
edit_document_number = '[NAME:ctxtDocumentNumber]'
edit_expiry_date = '[NAME:cdtpExpiryDate]'
edit_address_zipcode = '[NAME:ctxtAddressZipCode]'
edit_address_statecode = '[NAME:pnlAddressStateCode]'
edit_placeofbirth = '[NAME:ctxtPlaceOfBirth]'
combo_country_of_residence = '[NAME:ccboCountryOfResidence]'
edit_cityofresidence = '[NAME:ctxtCityOfResidence]'
combo_countryofvisa = '[NAME:ccboVisaCountry]'
edit_placeofissue = '[NAME:ctxtVisaPlaceOfIssue]'
edit_document_number_visa = '[NAME:ctxtVisaDocumentNumber]'
date_visa_issue_date = '[NAME:cdtpVisaIssueDate]'
edit_last_name_sfpd = '[NAME:ctxtLastNameSFPD]'
text_apis_passenger_and_travel_document_details = '[NAME:grpAPISPassengerDetails]'
text_address_sfpd = '[NAME:grpAPISAddress]'
text_secure_flight_passenger_data = '[NAME:grpSFPD]'
text_apis_other_information_and_visa_details = '[NAME:grpAPISOtherInfo]'

#
# -------------------------------- End of file -------------------------------------
