#***Variables***
#Documentation: Houses all the control objects for PEX Delivery Panel only.
#
# Delivery panel objects
#
label_receive_itinerary = '[NAME:lblReceiveItinerary]'
label_receive_invoice = '[NAME:lblReceiveInvoice]'
button_addrecipients = '[NAME:btnAddEmailControls]'
check_box_primaryemail = '[NAME:cchkItinerary0]'
check_box_primaryinvoice = '[NAME:chkInvoice0]'
check_box_primaryinvoice_1 = '[NAME:chkInvoice1]'
text_recipient_default = '[NAME:ctxtEmail0]'
text_addrecipients_1 = '[NAME:ctxtEmail1]'
text_addrecipients_2 = '[NAME:ctxtEmail2]'
text_addrecipients_3 = '[NAME:ctxtEmail3]'
check_box_addrecipients = '[NAME:cchkItinerary0]'
check_box_addrecipients_1 = '[NAME:cchkItinerary1]'
check_box_addrecipients_2 = '[NAME:cchkItinerary2]'
combo_deliverMethod = '[NAME:ccboDeliveryMethod]'
date_ticketing = '[NAME:uccTicketingDate]'
label_date_followup = '[NAME:lblFollowupDate]'
date_followup = '[NAME:uccFollowupDate]'
check_box_holdreason0 = '[NAME:UchkHoldReason0]'
check_box_holdreason1 = '[NAME:UchkHoldReason1]'
check_box_holdreason2 = '[NAME:UchkHoldReason2]'
check_box_holdreason3 = '[NAME:UchkHoldReason3]'
check_box_holdreason4 = '[NAME:UchkHoldReason4]'
check_box_holdreason5 = '[NAME:UchkHoldReason5]'
check_box_segment_order = '[NAME:chkSegmentOrder]'
text_segment_order = '[NAME:txtSegmentOrder]'
edit_awaiting_itinerary_segment = '[NAME:ctxtHoldReason]'
edit_text_header = '[NAME:txtHeader]'
select_segment_textbox = '[NAME:ctxtSegment]'
combo_itineraryFormat = '[NAME:ccboItineraryFormat]'
select_ticket_textbox = '[NAME:ctxtTicket]'
check_box_supress_ticket_information = '[NAME:cchkSupressTicket]'
check_box_supress_fare_information = '[NAME:cchkSupressFare]'
advanced_option_currency = '[NAME:ccboCurrency]'
advanced_option_fee = '[NAME:ctxtFee]'
advanced_option_ticket = '[NAME:ctxtFFTicket]'
advanced_option_add_button = '[NAME:btnAddFee]'
advanced_option_remove_button = '[NAME:btnRemoveFee]'
combo_team_id = '[NAME:cboTeam]'
edit_ticket_text = '[NAME:txtTicket]'
check_box_do_not_send_itinerary = '[NAME:chkDoNotSendItinerary]'
check_box_do_not_send_to_OBT = '[NAME:chkDoNotSendToOBT]'
ccombo_ticketing_time_limit = '[NAME:ccboTimeLimit]'
ctext_time_limit_remarks = '[NAME:ctxtTimeRemarks]'
group_ticketing_details = '[NAME:grpTicketingDetails]'
group_segment_order = '[NAME:grpSegmentOrder]'
check_segment_order = '[NAME:chkSegmentOrder]'
text_segment_order = '[NAME:txtSegmentOrder]'
button_subject_line = '[NAME:btnSubjectLine]'
opt_select_from_list = '[NAME:uxSelectFromListOption]'
combo_select_from_list = '[NAME:uxPreselected]'
opt_enter_free_text = '[NAME:uxEnterFreeTextOption]'
button_subject_line_ok = '[NAME:uxOK]'
button_subject_line_cancel = '[NAME:uxCancel]'
title_subject_line = 'Subject Line'
label_quick_amend = '[NAME:lblQuickAmend]'
button_quick_amend = '[NAME:btnQuickAmend]'


#
# -------------------------------- End of file -------------------------------------
